/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.au.cc.gallery;

import java.util.Map;
import java.util.HashMap;
import java.sql.ResultSet;
import java.sql.SQLException;

import static spark.Spark.*;

import spark.ModelAndView;

import spark.template.handlebars.HandlebarsTemplateEngine;

public class App {
    	public String getGreeting() {
        	return "Hello David.";
    	}

//	private static String listUsers() {
//	try {
//		StringBuffer sb = new StringBuffer();
//		UserDAO dao = Postgres.getUserDAO();
//		for(User u: dao.getUsers())
//			sb.append(u.toString() +"<br/>");
//		return sb.toString();
//	} catch (Exception e) {
//		return "Error: " + e.getMessage();
//		}
//	}
    	public static void main(String[] args) throws Exception {
//		port(5000);
//		get("/users", (req, res) -> listUsers());

		String portString = System.getenv("JETTY_PORT");
           		if (portString == null || portString.equals("")) {
             		port(5000);
           	}  else {
           		port(Integer.parseInt(portString));
	  	}

		Routes.connectToDatabase();
		new Routes().addRoutes();

//		DB db = new DB();
		//UserAdmin.main(null);
//		DB.demo();
    }
}
