/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.au.cc.gallery;

import java.util.*;
import java.util.Map;
import java.util.HashMap;

import static spark.Spark.*;
import spark.ModelAndView;
import spark.template.handlebars.HandlebarsTemplateEngine;
import spark.Request;
import spark.Response;
import java.sql.ResultSet;

import java.sql.SQLException;

public class Routes {

	private static DB db = new DB();

	public static void connectToDatabase() throws SQLException {
	db.connect();
	}

	public void addRoutes() {
	get("/admin", (req, res) -> adminPage(req, res));
	get("/admin/deleteUser/:user", (req, res) -> deleteUser(req, res));
//	get("/admin/modifyUser/:user", (req, res) -> modifyUser(req, res));

	}

	public String adminPage(Request req, Response res) {
	Map<String, Object> model = new HashMap<String, Object>();
	ResultSet rs;
	ArrayList<String> entries = new ArrayList<String>();

	try {
	   rs = db.getUsers();
	   model.put("name", "Users");
	   while(rs.next()) {
		entries.add(rs.getString(1));
	}
	   model.put("users", entries);
   	   return new HandlebarsTemplateEngine().render(new ModelAndView(model, "admin.hbs"));
	} catch (SQLException e) {
	   System.out.println(e);
	}
	return "";
	}

	public String deleteUser(Request req, Response res) {
	Map<String, Object> model = new HashMap<String, Object>();
	model.put("username", ":user");
	return new HandlebarsTemplateEngine().render(new ModelAndView(model, "deleteUser.hbs"));
	}

//	public void modifyUser(String username, Request req, Response res) {
//	Map<String, Object> model = new HashMap<String, Object>();
//	Result rs;

//	try{
//
//	} catch (SQLException e) {
//	   System.out.println(e);
//	}

}
