/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.au.cc.gallery;

import java.util.*;
import java.util.Map;
import java.util.HashMap;

import static spark.Spark.*;
import spark.ModelAndView;
import spark.template.handlebars.HandlebarsTemplateEngine;
import spark.Request;
import spark.Response;
import java.sql.ResultSet;

import java.sql.SQLException;

public class Routes {

	private static DB db = new DB();

	public static void connectToDatabase() throws SQLException {
	db.connect();
	}

	public void addRoutes() {
	get("/admin", (req, res) -> adminPage(req, res));
	get("/admin/deleteUser/:user", (req, res) -> deleteUser(req.params(":user"), res));
	post("/admin/deleteUser/:user", (req, res) -> postDeleteUser(req.params(":user"), res));

	get("/admin/addUser", (req, res) -> addUser(req, res));
	post("/admin/addUser", (req, res) -> postAddUser(req.queryParams("username"), req.queryParams("pwd"), req.queryParams("full_name"), res));

	get("/admin/modifyUser/:user", (req, res) -> modifyUser(req.params(":user"), res));
	post("/admin/modifyUser/:user", (req, res) -> postModifyUser(req.params(":user"), req.queryParams("pwd"), req.queryParams("full_name"), res));

	}

	public String adminPage(Request req, Response res) {
	Map<String, Object> model = new HashMap<String, Object>();
	ResultSet rs;
	ArrayList<String> entries = new ArrayList<String>();

	try {
	   rs = db.getUsers();
	   model.put("name", "Users");
	   while(rs.next()) {
		entries.add(rs.getString(1));
	}
	   model.put("users", entries);
   	   return new HandlebarsTemplateEngine().render(new ModelAndView(model, "admin.hbs"));
	} catch (SQLException e) {
	   System.out.println(e);
	}
	   return "";
	}

	public String addUser(Request req, Response res) {
	   Map<String, Object> model = new HashMap<String, Object>();
           return new HandlebarsTemplateEngine().render(new ModelAndView(model, "addUser.hbs"));
	   }

	public String postAddUser(String username, String password, String fullname, Response res) {
	   Map<String, Object> model = new HashMap<String, Object>();
	   try {
	      db.addUser(username, password, fullname);
	      res.redirect("/admin");
	      return "";
	   } catch (Exception e) {
		System.out.println(e);
	   }
	     return "";
	}

	public String deleteUser(String username, Response res) {
	Map<String, Object> model = new HashMap<String, Object>();
	try {
           model.put("user", username);
	   return new HandlebarsTemplateEngine().render(new ModelAndView(model, "deleteUser.hbs"));
	} catch (Exception e) {
	   System.out.println(e);
	}
	   return "";
	}

	public String postDeleteUser(String username, Response res) {
        Map<String, Object> model = new HashMap<String, Object>();
        try {
	   db.deleteUser(username);
           model.put("user", username);
	   res.redirect("/admin");
	   return "";
        } catch (Exception e) {
           System.out.println(e);
        }
           return "";
        }

	public String modifyUser(String username, Response res) {
	Map<String, Object> model = new HashMap<String, Object>();
	try{
           model.put("user", username);
           return new HandlebarsTemplateEngine().render(new ModelAndView(model, "modifyUser.hbs"));
	} catch (Exception e) {
	   System.out.println(e);
	}
	   return "";
	}

	public String postModifyUser(String username, String password, String fullname, Response res) {
	Map<String, Object> model = new HashMap<String, Object>();
	try{
           db.modifyUser(username, password, fullname);
	   res.redirect("/admin");
	   return "";
	} catch (SQLException e) {
	   System.out.println(e);
	}
	return "";
	}

}
